<div>
    <ul class="breadcrumb">
            <li>
                    <a href="/admin/proveedor/">Proveedores</a> <span class="divider">/</span>
            </li>
            <li>
                    <a href="/admin/proveedor/crear">Crear Proveedor</a>
            </li>
    </ul>
</div>
<div class="row-fluid sortable ui-sortable">		
    <div class="box span12">
        <div class="box-header well" data-original-title="">
            <h2><i class="icon-user"></i>Listado de Proveedores</h2>
            <div class="box-icon">
                <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" 
                       id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" role="columnheader"
                                           tabindex="0" aria-controls="DataTables_Table_0" 
                                           rowspan="1" colspan="1" 
                                           style="width: 196px;" aria-sort="ascending" 
                                           aria-label="Username: activate to sort column descending">
                                Razon Social
                            </th>
                            <th class="sorting" role="columnheader" tabindex="0"
                                aria-controls="DataTables_Table_0" rowspan="1" colspan="1" 
                                style="width: 163px;" aria-label="Date registered: activate to sort column ascending">
                                Tipo Documento
                            </th>
                            <th class="sorting" role="columnheader" tabindex="0" 
                                aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 92px;" 
                                aria-label="Role: activate to sort column ascending">
                                Nro. Doc.
                            </th>
                            <th class="sorting" role="columnheader" tabindex="0" 
                                aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 92px;" 
                                aria-label="Role: activate to sort column ascending">
                                Telefono
                            </th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                rowspan="1" colspan="1" style="width: 90px;" 
                                aria-label="Status: activate to sort column ascending">
                                Estado
                            </th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                rowspan="1" colspan="1" style="width: 366px;" 
                                aria-label="Actions: activate to sort column ascending">
                                Acciones
                            </th>
                        </tr>
                    </thead>   
                    <tbody role="alert" aria-live="polite" aria-relevant="all">
                        <?php
                       foreach ($this->listaProveedor as $proveedor):
                           $foco = 0;
                      ?>
                        <tr class="odd">
                            <td class="  sorting_1"><?php echo $proveedor['razonSocial']?></td>
                            <td class="center "><?php echo $proveedor['tipoDocumento']?></td>
                            <td class="center "><?php echo $proveedor['numeroDocumento']?></td>
                            <td class="center "><?php echo $proveedor['telefono']?></td>
                            <td class="center ">
                                <?php if($proveedor['estado']== 0):
                                $foco = 1;    
                                ?>
                                <span class="label label-important">Eliminado</span>
                                <?php endif;?>
                                <?php if($proveedor['estado']== 1): ?>
                                <span class="label label-success">Activo</span>
                                <?php endif;?>
                            </td>
                            <td class="center ">
                                <a class="btn btn-info" href="/admin/proveedor/editar/id/<?php echo $proveedor["idproveedor"]; ?>">
                                    <i class="icon-edit icon-white"></i>  
                                    Edit                                            
                                </a>
                                <?php if ($foco == 1) { ?>
                                <a class="btn btn-success" href="/admin/proveedor/activar/id/<?php echo $proveedor["idproveedor"]; ?>">
                                    <i class="icon-zoom-in icon-white"></i> 
                                    Activar
                                </a>
                                <?php }?>
                                <?php if ($foco == 0) { ?>
                                <a class="btn btn-danger" href="/admin/proveedor/eliminar/id/<?php echo $proveedor["idproveedor"]; ?>">
                                    <i class="icon-trash icon-white"></i> 
                                    Delete
                                </a>
                                <?php }?>
                            </td>
                        </tr>
                        <?php  endforeach; ?>
                        </tbody></table>
                <!--<div class="row-fluid"><div class="span12"><div class="dataTables_info" id="DataTables_Table_0_info">Showing 1 to 10 of 32 entries</div></div><div class="span12 center"><div class="dataTables_paginate paging_bootstrap pagination"><ul><li class="prev disabled"><a href="#">← Previous</a></li><li class="active"><a href="#">1</a></li><li><a href="#">2</a></li><li><a href="#">3</a></li><li><a href="#">4</a></li><li class="next"><a href="#">Next → </a></li></ul></div></div>
                </div>-->
                
            </div>            
        </div>
    </div><!--/span-->

</div>