<form class="" method="post" enctype="multipart/form-data" autocomplete="off">
<div class="container">
    <div class="row">
        <div class="alert-message warning span5 offset4" id="hint">            
            
            <table>
                <tr>
                    <td colspan="2">
                        <h3>BIENVENIDO</h3><br>
                        
                        
                        <h5>    <span>Estás tratando de acceder a un lugar Restringido <br>
                                Ingresa tus datos de acceso
                            </h5>
                            </span>
                    </td>
                </tr>
                <tr>
                    <td>Email : </td>
                    <td><input type="text" name="email"/> </td>
                </tr>
                <tr>
                    <td>Password : </td>
                    <td><input type="password" name="clave"/></td>
                </tr>
                <tr style="text-align: center">
                    <td colspan="2"><input type="button" class="btn" name="email" value="INGRESAR"/></td>
                </tr>
                <tr>
                    <td colspan="2"><?php //echo $this->form->auth_hash ?></td>
                    <input type="hidden" name="csrf" id="csrf" value="<?php echo $this->csrf?>"/>
                </tr>                
            </table>
        </div>
    </div>
</div>
</form>
<div id="fmsgs">
    <? if($this->fmsgs):
        foreach ($this->fmsgs as $msg): ?>
        <div class="alert <?= $msg->level == 'debug' ? 'error block-message' : $msg->level ?>">           
            <?= $msg->message ?>
        </div>            
    <? endforeach; endif;?>
</div>
