<div class="row-fluid sortable ui-sortable">		
    <div class="box span12">

        <div class="box-content">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                rowspan="1" colspan="1" style="width: 194px;" aria-sort="ascending" 
                                aria-label="Username: activate to sort column descending">
                                    id
                            </th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                rowspan="1" colspan="1" style="width: 168px;" aria-label="Date registered: activate to sort column ascending">
                                    Servicio
                            </th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" 
                                colspan="1" style="width: 363px;" aria-label="Actions: activate to sort column ascending">
                                Acciones
                            </th>
                        </tr>
                    </thead>   

                    <tbody role="alert" aria-live="polite" aria-relevant="all">
                      <?php
                       foreach ($this->listaServicio as $servicio):
                      ?>
                      <tr class="odd">
                            <td class="  sorting_1"><?php echo $servicio['idservicio'];?></td>
                            <td class="center "><?php echo $servicio['nombreServicio'];?></td>
                            <td class="center ">
                                <a class="btn btn-info" href="/admin/servicio/editar/id/<?php echo $servicio["idservicio"]; ?>">
                                    <i class="icon-edit icon-white"></i>  
                                    Editar                                            
                                </a>
                                <a class="btn btn-danger" href="/admin/servicio/eliminar/id/<?php echo $servicio["idservicio"]; ?>">
                                    <i class="icon-trash icon-white"></i> 
                                    Eliminar
                                </a>
                            </td>
                        </tr>
                        <?php
                        endforeach;
                        ?>
                        
                        </tbody>
                    </table>
                
            </div>            
        </div>
    </div><!--/span-->

</div>