<div class="well sidebar-nav span10">
<ul class="nav nav-list">    
    <li class="nav-header">ACCESOS RAPIDOS A:</li>
    <li class="nav-header">MANTENIMIENTOS</li>
    <li><a href="/admin/usuario/">Usuarios</a></li>
    <li><a href="/admin/cliente/">Clientes</a></li>
    <li><a href="/admin/servicio">Servicios</a></li>
    <li><a href="/admin/proveedor/">Proveedores</a></li>
    <li><a href="/admin/categoria/">Categoria</a></li>
    <li><a href="/admin/subcategoria/">Subcategoria</a></li>
    <li><a href="/admin/producto/">Productos</a></li>
    

</ul>
</div>

