<?=$this->doctype()?>

<html lang="en">
    <head>        
        <?=$this->headTitle()?>
        <?=$this->headMeta()?>
        <link id="bs-css" href="<?php echo SITE_URL ?>static/css/bootstrap-cerulean.css" rel="stylesheet">
        <style type="text/css">
	  body {
		padding-bottom: 40px;
	  }
	  .sidebar-nav {
		padding: 9px 0;
	  }
       </style>
       	<link href="<?php echo SITE_URL ?>static/css/bootstrap-responsive.css" rel="stylesheet">
	<link href="<?php echo SITE_URL ?>static/css/charisma-app.css" rel="stylesheet">
	<link href="<?php echo SITE_URL ?>static/css/jquery-ui-1.8.21.custom.css" rel="stylesheet">
	<link href='<?php echo SITE_URL ?>static/css/fullcalendar.css' rel='stylesheet'>
	<link href='<?php echo SITE_URL ?>static/css/fullcalendar.print.css' rel='stylesheet'  media='print'>
	<link href='<?php echo SITE_URL ?>static/css/chosen.css' rel='stylesheet'>
	<link href='<?php echo SITE_URL ?>static/css/uniform.default.css' rel='stylesheet'>
	<link href='<?php echo SITE_URL ?>static/css/colorbox.css' rel='stylesheet'>
	<link href='<?php echo SITE_URL ?>static/css/jquery.cleditor.css' rel='stylesheet'>
	<link href='<?php echo SITE_URL ?>static/css/jquery.noty.css' rel='stylesheet'>
	<link href='<?php echo SITE_URL ?>static/css/noty_theme_default.css' rel='stylesheet'>
	<link href='<?php echo SITE_URL ?>static/css/elfinder.min.css' rel='stylesheet'>
	<link href='<?php echo SITE_URL ?>static/css/elfinder.theme.css' rel='stylesheet'>
	<link href='<?php echo SITE_URL ?>static/css/jquery.iphone.toggle.css' rel='stylesheet'>
	<link href='<?php echo SITE_URL ?>static/css/opa-icons.css' rel='stylesheet'>
	<link href='<?php echo SITE_URL ?>static/css/uploadify.css' rel='stylesheet'>
        <?=$this->headLink()?>
        <?=$this->headScript()?>
        <?=$this->headStyle()?>
        
    </head>
    <body>
        
        <?= $this->render('_topbar-admin.phtml');?>
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span3">
                    <?=$this->render('_sidebar-admin.phtml');?>
                </div>
                <div class="span9">
                <div class="content" class="span10">
                        <?=$this->render('_messages.phtml');?>
                        <?=$this->layout()->content?>
                </div>
                </div>    
                
            </div>
            <div class="content">
            <?=$this->render('_footer-admin.phtml');?>
            </div>
        </div>
        	<!-- jQuery -->
	<script src="<?php echo SITE_URL ?>static/js/jquery-1.7.2.min.js"></script>
	<!-- jQuery UI -->
	<script src="<?php echo SITE_URL ?>static/js/jquery-ui-1.8.21.custom.min.js"></script>
	<!-- transition / effect library -->
	<script src="<?php echo SITE_URL ?>static/js/bootstrap-transition.js"></script>
	<!-- alert enhancer library -->
	<script src="<?php echo SITE_URL ?>static/js/bootstrap-alert.js"></script>
	<!-- modal / dialog library -->
	<script src="<?php echo SITE_URL ?>static/js/bootstrap-modal.js"></script>
	<!-- custom dropdown library -->
	<script src="<?php echo SITE_URL ?>static/js/bootstrap-dropdown.js"></script>
	<!-- scrolspy library -->
	<script src="<?php echo SITE_URL ?>static/js/bootstrap-scrollspy.js"></script>
	<!-- library for creating tabs -->
	<script src="<?php echo SITE_URL ?>static/js/bootstrap-tab.js"></script>
	<!-- library for advanced tooltip -->
	<script src="<?php echo SITE_URL ?>static/js/bootstrap-tooltip.js"></script>
	<!-- popover effect library -->
	<script src="<?php echo SITE_URL ?>static/js/bootstrap-popover.js"></script>
	<!-- button enhancer library -->
	<script src="<?php echo SITE_URL ?>static/js/bootstrap-button.js"></script>
	<!-- accordion library (optional, not used in demo) -->
	<script src="<?php echo SITE_URL ?>static/js/bootstrap-collapse.js"></script>
	<!-- carousel slideshow library (optional, not used in demo) -->
	<script src="<?php echo SITE_URL ?>static/js/bootstrap-carousel.js"></script>
	<!-- autocomplete library -->
	<script src="<?php echo SITE_URL ?>static/js/bootstrap-typeahead.js"></script>
	<!-- tour library -->
	<script src="<?php echo SITE_URL ?>static/js/bootstrap-tour.js"></script>
	<!-- library for cookie management -->
	<script src="<?php echo SITE_URL ?>static/js/jquery.cookie.js"></script>
	<!-- calander plugin -->
	<script src='<?php echo SITE_URL ?>static/js/fullcalendar.min.js'></script>
	<!-- data table plugin -->
	<script src='<?php echo SITE_URL ?>static/js/jquery.dataTables.min.js'></script>

	<!-- chart libraries start -->
	<script src="<?php echo SITE_URL ?>static/js/excanvas.js"></script>
	<script src="<?php echo SITE_URL ?>static/js/jquery.flot.min.js"></script>
	<script src="<?php echo SITE_URL ?>static/js/jquery.flot.pie.min.js"></script>
	<script src="<?php echo SITE_URL ?>static/js/jquery.flot.stack.js"></script>
	<script src="<?php echo SITE_URL ?>static/js/jquery.flot.resize.min.js"></script>
	<!-- chart libraries end -->

	<!-- select or dropdown enhancer -->
	<script src="<?php echo SITE_URL ?>static/js/jquery.chosen.min.js"></script>
	<!-- checkbox, radio, and file input styler -->
	<script src="<?php echo SITE_URL ?>static/js/jquery.uniform.min.js"></script>
	<!-- plugin for gallery image view -->
	<script src="<?php echo SITE_URL ?>static/js/jquery.colorbox.min.js"></script>
	<!-- rich text editor library -->
	<script src="<?php echo SITE_URL ?>static/js/jquery.cleditor.min.js"></script>
	<!-- notification plugin -->
	<script src="<?php echo SITE_URL ?>static/js/jquery.noty.js"></script>
	<!-- file manager library -->
	<script src="<?php echo SITE_URL ?>static/js/jquery.elfinder.min.js"></script>
	<!-- star rating plugin -->
	<script src="<?php echo SITE_URL ?>static/js/jquery.raty.min.js"></script>
	<!-- for iOS style toggle switch -->
	<script src="<?php echo SITE_URL ?>static/js/jquery.iphone.toggle.js"></script>
	<!-- autogrowing textarea plugin -->
	<script src="<?php echo SITE_URL ?>static/js/jquery.autogrow-textarea.js"></script>
	<!-- multiple file upload plugin -->
	<script src="<?php echo SITE_URL ?>static/js/jquery.uploadify-3.1.min.js"></script>
	<!-- history.js for cross-browser state change on ajax -->
	<script src="<?php echo SITE_URL ?>static/js/jquery.history.js"></script>
	<!-- application script for Charisma demo -->
	<script src="<?php echo SITE_URL ?>static/js/charisma.js"></script>
    </body>
</html>