<?php echo $this->doctype()?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Administrador OferTop</title>
        <link rel="stylesheet" href="<?php echo MEDIA_URL?>/css/styles/bootstrap/datepicker.css"/>
        <link rel="stylesheet" href="<?php echo MEDIA_URL?>/css/styles/admin.css"/>
        <link rel="stylesheet" href="<?php echo MEDIA_URL?>/css/styles/patch.css"/>        
        
        <?php echo $this->headLink()?>        
    </head>
    <body id="loginbox">
    <?php
            $ruta=Zend_Controller_Action_HelperBroker::getStaticHelper('Redirector')->getRequest()->getRequestUri();
            if($ruta=='/retailer')
            {
                $tag = "otros.retailer";
        ?>
        <!-- Begin comScore Inline Tag 1.1111.15 -->
        <script type="text/javascript">
            // <![CDATA[
            function udm_(a){var b="comScore=",c=document,d=c.cookie,e="",f="indexOf",g="substring",h="length",i=2048,j,k="&ns_",l="&",m,n,o,p,q=window,r=q.encodeURIComponent||escape;if(d[f](b)+1)for(o=0,n=d.split(";"),p=n[h];o<p;o++)m=n[o][f](b),m+1&&(e=l+unescape(n[o][g](m+b[h])));a+=k+"_t="+ +(new Date)+k+"c="+(c.characterSet||c.defaultCharset||"")+"&c8="+r(c.title)+e+"&c7="+r(c.URL)+"&c9="+r(c.referrer),a[h]>i&&a[f](l)>0&&(j=a[g](0,i-8).lastIndexOf(l),a=(a[g](0,j)+k+"cut="+r(a[g](j+1)))[g](0,i)),c.images?(m=new Image,q.ns_p||(ns_p=m),m.src=a):c.write("<","p","><",'img src="',a,'" height="1" width="1" alt="*"',"><","/p",">")}
            udm_('http'+(document.location.href.charAt(4)=='s'?'s://sb':'://b')+'.scorecardresearch.com/b?c1=2&c2=6906602&ns_site=ofertop&name=<?php echo $tag?>');
            // ]]>
        </script>
        <noscript><p><img src="http://b.scorecardresearch.com/p?c1=2&amp;c2=6906602&amp;ns_site=ofertop&amp;name=<?php echo $tag?>" height="1" width="1" alt="*"></p></noscript>
        <!-- End comScore Inline Tag -->
        <?php }?>
            <?php echo $this->layout()->content?>
        <?php if($ruta=='/retailer')
            {?>
        <script language="JavaScript1.3" src="http://b.scorecardresearch.com/c2/6906602/ct.js"></script>
    <?php } ?>
    </body>
</html>