<?php echo $this->doctype()?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Administrador</title>
        <link rel="stylesheet" href="<?php echo MEDIA_URL?>/css/styles/admin.css"/>
        <link rel="stylesheet" href="<?php echo MEDIA_URL?>/css/styles/patch.css"/>        
        
        <?php echo $this->headLink()?>        
    </head>
    <body>
        <?php echo $this->layout()->content?>
    </body>
</html>