<div>
    <ul class="breadcrumb">
            <li>
                <a href="#"> Clientes </a> <span class="divider">/</span>
            </li>
            <li>
                <a href="/admin/cliente/crear">Crear Cliente</a>
            </li>
    </ul>
</div>
<div class="row-fluid sortable ui-sortable">		
    <div class="box span12">
        <div class="box-header well" data-original-title="">
            <h2><i class="icon-user"></i>Listado de Clientes</h2>
            <div class="box-icon">                
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>                
            </div>
        </div>
        <div class="box-content">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" 
                       id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" role="columnheader"
                                           tabindex="0" aria-controls="DataTables_Table_0" 
                                           rowspan="1" colspan="1" 
                                           style="width: 140px;" aria-sort="ascending" 
                                           aria-label="Username: activate to sort column descending">
                                Nombre
                            </th>
                            <th class="sorting" role="columnheader" tabindex="0"
                                aria-controls="DataTables_Table_0" rowspan="1" colspan="1" 
                                style="width: 140px;" aria-label="Date registered: activate to sort column ascending">
                                Apellido
                            </th>
                            <th class="sorting" role="columnheader" tabindex="0" 
                                aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 140px;" 
                                aria-label="Role: activate to sort column ascending">
                                Email
                            </th>
                            <th class="sorting" role="columnheader" tabindex="0" 
                                aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 80px;" 
                                aria-label="Role: activate to sort column ascending">
                                Teléfono
                            </th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                rowspan="1" colspan="1" style="width: 90px;" 
                                aria-label="Status: activate to sort column ascending">
                                Fecha Registro
                            </th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                rowspan="1" colspan="1" style="width: 80px;" 
                                aria-label="Actions: activate to sort column ascending">
                                Acciones
                            </th>
                        </tr>
                    </thead>   
                    <tbody role="alert" aria-live="polite" aria-relevant="all">
                        <?php
                       foreach ($this->listaUsuario as $usuario):
                           $foco = 0;
                      ?>
                        <tr class="odd">
                            <td class="  sorting_1"><?php echo $usuario['nombre']?></td>
                            <td class="center "><?php echo $usuario['apellido']?></td>
                            <td class="center "><?php echo $usuario['email']?></td>
                            <td class="center "><?php echo $usuario['telefono']?></td>
                            <td class="center ">
                                <?php echo   $usuario['fechaRegistro']?>
                            </td>
                            <td class="center ">
                                <a class="btn btn-info" href="/admin/usuario/editar/id/<?php echo $usuario["idusuario"]; ?>">
                                    <i class="icon-edit icon-white"></i>  
                                    Edit                                            
                                </a>
                                <?php if ($foco == 1) { ?>
                                <a class="btn btn-success" href="/admin/usuario/activar/id/<?php echo $usuario["idusuario"]; ?>">
                                    <i class="icon-zoom-in icon-white"></i> 
                                    Activar
                                </a>
                                <?php }?>
                                <?php if ($foco == 0) { ?>
                                <a class="btn btn-danger" href="/admin/usuario/eliminar/id/<?php echo $usuario["idusuario"]; ?>">
                                    <i class="icon-trash icon-white"></i> 
                                    Delete
                                </a>
                                <?php }?>
                            </td>
                        </tr>
                        <?php  endforeach; ?>
                        </tbody></table>
                <!--<div class="row-fluid"><div class="span12"><div class="dataTables_info" id="DataTables_Table_0_info">Showing 1 to 10 of 32 entries</div></div><div class="span12 center"><div class="dataTables_paginate paging_bootstrap pagination"><ul><li class="prev disabled"><a href="#">← Previous</a></li><li class="active"><a href="#">1</a></li><li><a href="#">2</a></li><li><a href="#">3</a></li><li><a href="#">4</a></li><li class="next"><a href="#">Next → </a></li></ul></div></div>
                </div>-->
                
            </div>            
        </div>
    </div><!--/span-->

</div>