<ul class="breadcrumb">    
    <li>
        <a href="/admin/producto">Productos</a> <span class="divider">/</span>
    </li>    
</ul>
<div id="content_wrapper">
     <div id="content">
         <div class="inner">
             <form action="" method="post" enctype="multipart/form-data" class="well" id="formProd">
                <div class="header">
                    <h3>Registrar Productos</h3>
                </div>
                 <hr />
                <div class="row-fluid">
                    <div class="span10">
                        <div class="clear"></div>
                        
                        <label for="nombre" class="span4 no-margin">Código Producto :</label>
                        <div class="span6 no-margin">
                            <?php echo $this->form->codigo->setAttrib('maxlength', '10')->renderViewHelper();?>
                            <?php if ($this->form->codigo->hasErrors()) echo "Ingresa Código Correcto";?>
                        </div>                        
                        <div class="clear"></div>                                                
                        
                        <label for="nombreProducto" class="span4 no-margin">Nombre Producto :</label>
                        <div class="span6 no-margin">
                            <?php echo $this->form->nombreProducto->setAttrib('maxlength', '50')->renderViewHelper();?>
                            <?php if ($this->form->nombreProducto->hasErrors()) echo "Ingresa nombre para el producto";?>
                        </div>                                                                        
                        <div class="clear"></div>
                        
                        <label for="servicio" class="span4 no-margin">Servicio :</label>
                        <div class="span6 no-margin">
                            <?php echo $this->form->idservicio;?>
                        </div>                                                
                        <div class="clear"></div>
                        
                        <label for="categoria" class="span4 no-margin">Categoria :</label>
                        <div class="span6 no-margin">
                            <?php echo $this->form->categoria;?>
                        </div>
                        <div class="clear"></div>
                        
                        <label for="categoria" class="span4 no-margin">Sub - Categoria :</label>
                        <div class="span6 no-margin">
                            <?php echo $this->form->subcategoria;?>
                        </div>
                        <div class="clear"></div>
                        
                        <label for="categoria" class="span4 no-margin">Proveedor :</label>
                        <div class="span6 no-margin">
                            <?php echo $this->form->proveedor;?>
                        </div>
                        <div class="clear"></div>
                        
                        <label for="fechaInicio" class="span4 no-margin">Fecha Inicio :</label>
                        <div class="span6 no-margin">
                            <?php echo $this->form->fechaInicio;?>
                        </div>
                        <div class="clear"></div>
                        
                        <label for="fechaFin" class="span4 no-margin">Fecha Fin :</label>
                        <div class="span6 no-margin">
                            <?php echo $this->form->fechaFin;?>
                        </div>
                        <div class="clear"></div>
                        
                        
                        <label for="precio" class="span4 no-margin">Precio :</label>
                        <div class="span6 no-margin">
                            <?php echo $this->form->precio->setAttrib('maxlength', '10')->renderViewHelper();?>
                        </div>                        
                        <div class="clear"></div>
                        
                        <label for="stock" class="span4 no-margin">Stock :</label>
                        <div class="span6 no-margin">
                            <?php echo $this->form->stock->renderViewHelper();?>
                        </div>                        
                        <div class="clear"></div>
                        
                        <label for="descripcionCorta" class="span4 no-margin">Descripción Corta :</label>
                        <div class="span6 no-margin">
                            <?php echo $this->form->descripcionCorta;?>
                        </div>                        
                        <div class="clear"></div>
                        
                        <label for="descripcionLarga" class="span4 no-margin">Descripción Completa :</label>
                        <div class="span6 no-margin">
                            <?php echo $this->form->descripcionLarga;?>
                        </div>                        
                        <div class="clear"></div>                        
                        <br>
                        <?php 
                        foreach ($this->foto as $value):
                            if ($value['orden'] == '0') {$p = 1;$name=$value['foto'];$id= $value['idproductoFoto'];}
                            if ($value['orden'] == '1') {$p1 = 1;$name1=$value['foto'];$id1= $value['idproductoFoto'];}
                            if ($value['orden'] == '2') {$p2 = 1;$name2=$value['foto'];$id2= $value['idproductoFoto'];}
                            if ($value['orden'] == '3') {$p3 = 1;$name3=$value['foto'];$id3= $value['idproductoFoto'];}
                            if ($value['orden'] == '4') {$p4 = 1;$name4=$value['foto'];$id4= $value['idproductoFoto'];}
                        endforeach;
                        
                        ?>
                        
                        <label for="fotoPrincipal" class="span4 no-margin">Foto Principal :</label>
                        <div class="span6 no-margin">
                            <?php                              
                            if(isset ($p)) { $a = ELEMENTS_URL. "/productos/" .$name;?>
                            <a href="<?php echo $a?>"> <?php echo $a?></a>
                            <strong> <a href="/admin/producto/eliminarfoto/id/<?php echo $id?>/prod/<?php echo $this->producto['idproducto']?>">Eliminar</a>
                                </strong>
                            <?php }else {
                            echo $this->form->fotoPrincipal;
                            if ($this->form->fotoPrincipal->hasErrors()) echo "Imagen inválida";
                            }
                            ?>     
                        </div>                        
                        <div class="clear"></div>
                        
                        <label for="foto1" class="span4 no-margin">Foto :</label>
                        <div class="span6 no-margin">
                            <?php                              
                            if(isset ($p1)) { $a = ELEMENTS_URL. "/productos/" .$name1;?>
                            <a href="<?php echo $a?>"> <?php echo $a?></a>
                            <strong> <a href="/admin/producto/eliminarfoto/id/<?php echo $id1?>/prod/<?php echo $this->producto['idproducto']?>">Eliminar</a>
                                </strong>
                            <?php }else {
                            echo $this->form->foto1;
                            if ($this->form->foto1->hasErrors()) echo "Imagen inválida";
                            }
                            ?>
                        </div>                        
                        <div class="clear"></div>
                        
                        <label for="foto2" class="span4 no-margin">Foto :</label>
                        <div class="span6 no-margin">
                            <?php                              
                            if(isset ($p2)) { $a = ELEMENTS_URL. "/productos/" .$name2;?>
                            <a href="<?php echo $a?>"> <?php echo $a?></a>
                            <strong> <a href="/admin/producto/eliminarfoto/id/<?php echo $id2?>/prod/<?php echo $this->producto['idproducto']?>">Eliminar</a>
                                </strong>
                            <?php }else {
                            echo $this->form->foto2;
                            if ($this->form->foto2->hasErrors()) echo "Imagen inválida";
                            }
                            ?>
                        </div>                        
                        <div class="clear"></div>
                        
                        <label for="foto3" class="span4 no-margin">Foto :</label>
                        <div class="span6 no-margin">
                            <?php                              
                            if(isset ($p3)) { $a = ELEMENTS_URL. "/productos/" .$name3;?>
                            <a href="<?php echo $a?>"> <?php echo $a?></a>
                            <strong> <a href="/admin/producto/eliminarfoto/id/<?php echo $id3?>/prod/<?php echo $this->producto['idproducto']?>">Eliminar</a>
                                </strong>
                            <?php }else {
                            echo $this->form->foto3;
                            if ($this->form->foto3->hasErrors()) echo "Imagen inválida";
                            }
                            ?>
                        </div>                        
                        <div class="clear"></div>
                        
                        <label for="foto4" class="span4 no-margin">Foto :</label>
                        <div class="span6 no-margin">
                            <?php                              
                            if(isset ($p4)) { $a = ELEMENTS_URL. "/productos/" .$name4;?>
                            <a href="<?php echo $a?>"> <?php echo $a?></a>
                            <strong> <a href="/admin/producto/eliminarfoto/id/<?php echo $id4?>/prod/<?php echo $this->producto['idproducto']?>">Eliminar</a>
                                </strong>
                            <?php }else {
                            echo $this->form->foto4;
                            if ($this->form->foto4->hasErrors()) echo "Imagen inválida";
                            }
                            ?>
                        </div>                        
                        <div class="clear"></div>
                        
                        <?php echo $this->form->csrf->renderViewHelper(); ?>
                        <?php if ($this->form->csrf->hasErrors()) echo "Intentalo nuevamente";?>
                    </div>
                    <div class="clear"></div>
                                        
                </div>
                <div class="form-actions">
                    <?php echo $this->form->guardar->setAttrib('class', 'btn pull-right')?>                    
                </div>
        </form>
    </div>
 </div>
</div>

<script src="<?php echo SITE_URL ?>static/js2/admin/producto.js"></script>

<script>
$("#subcategoria").removeAttr("disabled");
$(document).ready(function(){
    $('#fechaInicio').datepicker({
        format: 'yyyy-mm-dd',
        todayBtn: 'linked',
        language: 'es'
    });
    
    $('#fechaFin').datepicker({
        format: 'yyyy-mm-dd',
        todayBtn: 'linked',
        language: 'es'
    });    
        
});

$(function(){
    
    var producto = {        
        init : function() {
           this.Combo("#categoria", "#subcategoria", "--- Seleccionar ---", "/admin/categoria/get-categorias-ajax", "idcategoria", "descripcion");           
        },        
        Combo : function (c, cd, def, url, fieldv, fields) {
                
                var actual = $(c);
                
                if (actual.val() != 0) {
                    
                    $(cd).removeAttr("disabled");
                    $.ajax({
                        url: url,
                        type: 'post',
                        data: {
                           id : actual.val()
                        },
                        dataType: 'json',                        
                        success: function(data){
                                $(cd).html("<option value='0'> --Seleccionar-- </option>");
                                $.each(data, function(index, value){
                                    var select = ' ';
                                    if (value[fieldv] == '<?php echo $this->producto['subcategoria']?>')
                                        var selec = 'selected="selected "';
    
                                    
                                    $(cd).append("<option "+ selec +" value='"+value[fieldv]+"'>"+value[fields]+"</option>");
                                });
                        }
                    });                    
                } else {
                    $(cd).html("");
                    $(cd).append("<option value='0'>-- Seleccionar--</option>");
                    $(cd).attr("disabled", "disabled");
                    
                    
                }
            
       }
    };
    
    producto.init();
    
    
    
});


</script>
