<div>
				<ul class="breadcrumb">
					<li>
						<a href="/admin/producto">Productos</a> <span class="divider">/</span>
					</li>
					<li>
						<a href="/admin/producto/crear">Agregar Producto</a>
					</li>
				</ul>
			</div>
<div class="row-fluid sortable ui-sortable">		
    <div class="box span12">
        <div class="box-header well" data-original-title="">
            <h2><i class="icon-zoom-in"></i> Listado Productos</h2>
            <div class="box-icon">                
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>                
            </div>
        </div>
        <div class="box-content">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 196px;" aria-sort="ascending" aria-label="Username: activate to sort column descending">Descripción</th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 163px;" aria-label="Date registered: activate to sort column ascending">Date registered</th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 92px;" aria-label="Role: activate to sort column ascending">Role</th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 90px;" aria-label="Status: activate to sort column ascending">Status</th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 366px;" aria-label="Actions: activate to sort column ascending">Actions</th>
                        </tr>
                    </thead>   

                    <tbody role="alert" aria-live="polite" aria-relevant="all">
                        <tr class="odd">
                            <td class="  sorting_1">
                                Abdullah
                            </td>
                            <td class="center ">
                                2012/02/01
                            </td>
                            <td class="center ">
                                Staff
                            </td>
                            <td class="center ">
                                dasd
                            </td>
                            <td class="center ">
                                <a class="btn btn-info" href="#">
                                    <i class="icon-edit icon-white"></i>  
                                    Editar
                                </a>
                                <a class="btn btn-danger" href="#">
                                    <i class="icon-trash icon-white"></i> 
                                    Eliminar
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>                
            </div>            
        </div>
    </div><!--/span-->

</div>