<ul class="breadcrumb">    
    <li>
        <a href="/admin/categoria">Lista Categorías</a> <span class="divider">/</span>
    </li>    
</ul>
<div id="content_wrapper">
     <div id="content">
         <div class="inner">
             <form action="" method="post" enctype="multipart/form-data" class="well">
                <div class="header">
                    <h3>Crear Categoria</h3>
                    <hr>
                </div>
                <div class="row-fluid">
                    <div class="span9">
                        <div class="clear"></div>
                        <label for="descripción" class="span3 no-margin">Descripción Categoria:</label>
                        <div class="span9 no-margin">
                            <?php echo $this->form->descripcion->setAttrib('maxlength', '100')->renderViewHelper();?>
                            <?php if ($this->form->descripcion->hasErrors()) echo "Ingresa Descripción";?>
                        </div>
                        <div class="clear"></div>
                        <?php echo $this->form->csrf; ?>
                        <?php if ($this->form->csrf->hasErrors()) echo "Intentalo nuevamente";?>
                    </div>
                    <div class="clear"></div>
                                        
                </div>
                <div class="form-actions">
                    <?php echo $this->form->guardar->setAttrib('class', 'btn pull-right')?>
                </div>
        </form>
    </div>
 </div>
</div>

