<div>
    <ul class="breadcrumb">
            <li>
                    <a href="#">Categorias</a> <span class="divider">/</span>
            </li>
            <li>
                    <a href="/admin/categoria/crear">Crear Categoria</a>
            </li>
    </ul>
</div>
<div class="row-fluid sortable ui-sortable">		
    <div class="box span12">

        <div class="box-content">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
                    <thead>
                        <tr role="row">
                            <th tabindex="0" aria-controls="DataTables_Table_0" 
                                rowspan="1" colspan="1" style="width: 194px;">
                                    ID
                            </th>
                            <th role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                rowspan="1" colspan="1" style="width: 168px;">
                                    Categoria
                            </th>
                            <th role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                rowspan="1" colspan="1" style="width: 168px;">
                                    SubCategoria
                            </th>
                            <th role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" 
                                colspan="1" style="width: 363px;">
                                Acciones
                            </th>
                        </tr>
                    </thead>   

                    <tbody role="alert" aria-live="polite" aria-relevant="all">
                      <?php
                       foreach ($this->lista as $categoria):
                      ?>
                      
                          <?php if (is_null($categoria['padre'])){ ?> 
                        
                        <tr class="odd">    
                            <td><?php echo $categoria['idcategoria'];?></td>
                            <td class="center "><strong><?php   echo $categoria['descripcion'];?></strong></td>
                            <td class="center "><?php //echo $categoria['nombreServicio'];?></td>
                            <td class="center ">
                                <a class="btn btn-info" href="/admin/categoria/editar/id/<?php echo $categoria["idcategoria"]; ?>">
                                    <i class="icon-edit icon-white"></i>  
                                    Editar                                            
                                </a>
                                <a class="btn btn-info" href="/admin/categoria/agregar-subcategoria/id/<?php echo $categoria["idcategoria"]; ?>">
                                    <i class="icon-edit icon-white"></i>  
                                    Agregar 
                                </a>
                                <a class="btn btn-danger" href="/admin/categoria/updateestado/id/<?php echo $categoria["idcategoria"]; ?>/tipo/1/est/<?php echo $categoria["estado"]; ?>">
                                    <?php echo ($categoria['estado'] == 1)?'Desactivar':'Activar' ?> 
                                </a>
                                
                            </td>
                        </tr>
                          
                           <?php                   
                              
                          } else { ?>
                              <tr class="even">    
                            <td> <?php echo $categoria['idcategoria'];?></td>
                            <td class="center "> |__________________</td>
                            <td class="center "><strong> <?php echo $categoria['descripcion'];?> </strong></td>
                            <td class="center ">
                                <a class="btn btn-info" href="/admin/categoria/editar/id/<?php echo $categoria["cathija"]; ?>/tipo/2">
                                    <i class="icon-edit icon-white"></i>  
                                    Editar                                            
                                </a>
                                <a class="btn btn-danger" href="/admin/categoria/updateestado/id/<?php echo $categoria["cathija"]; ?>/est/<?php echo $categoria["estado"]; ?>">
                                    <?php echo ($categoria['estado'] == 1)?'Desactivar':'Activar' ?> 
                                </a>
                            </td>
                        </tr>
                      
                        <?php }
                        endforeach;
                        ?>
                        
                        </tbody>
                    </table>
                
            </div>            
        </div>
    </div><!--/span-->

</div>